name: trip_planner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.5
  formz: ^0.7.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  jiffy: ^6.3.1
  logger: ^2.3.0
  mysql1: ^0.20.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  riverpod: ^2.5.1
  share_plus: ^8.0.3
  shared_preferences: ^2.2.2
  stream_chat_flutter: ^8.0.0-beta.3
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/images/loading.gif
    - assets/images/nubes.gif
    - assets/images/Logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#000000"
