// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// com.cris:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjYvOUiUdUbsOBxs8ItxNMsHmP1x7_P6g',
    appId: '1:1047598233178:web:6439109966b8f452248a63',
    messagingSenderId: '1047598233178',
    projectId: 'tripplanner-7f54c',
    authDomain: 'tripplanner-7f54c.firebaseapp.com',
    storageBucket: 'tripplanner-7f54c.appspot.com',
    measurementId: 'G-WS1ZKK2J49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLE9rRVtrFbmdUkkN_u7B3odryDx_lP7s',
    appId: '1:1047598233178:android:b91bfa72aaa6ee13248a63',
    messagingSenderId: '1047598233178',
    projectId: 'tripplanner-7f54c',
    storageBucket: 'tripplanner-7f54c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUwe5V41-lRPMRWVyNId-qdUdDUaIZqcI',
    appId: '1:1047598233178:ios:c907ee5be18d8cf8248a63',
    messagingSenderId: '1047598233178',
    projectId: 'tripplanner-7f54c',
    storageBucket: 'tripplanner-7f54c.appspot.com',
    iosBundleId: 'com.cris.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUwe5V41-lRPMRWVyNId-qdUdDUaIZqcI',
    appId: '1:1047598233178:ios:c907ee5be18d8cf8248a63',
    messagingSenderId: '1047598233178',
    projectId: 'tripplanner-7f54c',
    storageBucket: 'tripplanner-7f54c.appspot.com',
    iosBundleId: 'com.cris.tripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjYvOUiUdUbsOBxs8ItxNMsHmP1x7_P6g',
    appId: '1:1047598233178:web:d208202bcdbc9d62248a63',
    messagingSenderId: '1047598233178',
    projectId: 'tripplanner-7f54c',
    authDomain: 'tripplanner-7f54c.firebaseapp.com',
    storageBucket: 'tripplanner-7f54c.appspot.com',
    measurementId: 'G-P147478YJR',
  );
}
